title: Learning to Build, Building to Learn.
description: Exploring the Depths of Data and Machine Learning, Journey Through Learning and Sharing.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true